apiVersion: v1
kind: Service
metadata:
  name: nodetestproj-svc
  labels:
    app: nodetestproj-svc
spec:
  type: NodePort
  ports:
  - port: 1236
    nodePort: 31236
  selector:
    app: nodetestproj-pod